### PR TITLE
Initialize rev before using &rev.pending

### LINKED ISSUE #2006: Segmentation fault running `git stash` with `git add -N` file
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init foo
cd foo
echo foo >foo
git add foo
git commit -m 'Add foo'
echo bar >bar
git add -N bar
git stash
```
 - What did you expect to occur after running these commands?

I expected Git to stash the changes to `bar`.

 - What actually happened instead?

Git produced the following output:

```
error: Entry 'bar' not uptodate. Cannot merge.
Segmentation fault
```

It also left behind `.git/lock`, so running `git stash` again produces the following output:

```
fatal: Unable to create 'C:/TEMP/foo/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It doesn't occur with a specific repository.

### PR DESCRIPTION
**Pull request by kraai**
If reset_tree returns a non-zero value, stash_working_tree calls
object_array_clear with &rev.pending before rev is initialized.  This
causes a segmentation fault.  Prevent this by initializing rev before
calling reset_tree.

This fixes #2006.

Signed-off-by: Matthew Kraai <mkraai@its.jnj.com>

### CODE REVIEW

File: t/t3903-stash.sh [hunk 1]
```diff
@@ -287,6 +287,14 @@ test_expect_success 'stash an added file' '
 	test new = "$(cat file3)"
 '
 
+test_expect_success 'stash --intent-to-add file' '
+	git reset --hard &&
+	echo new >file4 &&
+	git add --intent-to-add file4 &&
+	test_must_fail git stash &&
+	git rm -f file4
```
Comment (dscho) [inline t/t3903-stash.sh]: I think this should be moved up 1 line and should read `test_when_finished "git rm -f file4"` instead.

**Comment by dscho** [comment]
Thanks!
