### PR TITLE
http: Add support for enabling automatic sending of SSL client certificate

### LINKED ISSUE #3292: Git 2.32 cannot access git repositories secured using client certificates when using cURL schannel backend
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.1052]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

In the repositories where the problem occurs, a p12 client certificate is used. 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git fetch

```
 - What did you expect to occur after running these commands?

Git fetches changes.

 - What actually happened instead?

This error is shown: 
```
fatal: unable to access 'https://cmstash.cm.ict.nl/scm/pcs/deltawebclient.git/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
```

(This error is shown for all operations involving the remote repository, and is not limited to fetch)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I cannot provide the URL to the repository, as this is a repository only available to employees of the company I work at. Note that p12 certificates are used as a security measure. This seems to be related to the problem. 

**Important: I already did some research. This is what I figured out so far:**
 - This problem does not occur in the previous version ( Git for Windows v2.31.1 )
 - I could not find more information in the Windows System event log, even though the error suggests this. 
 - I tried setting GCM_TRACE=1 and GIT_TRACE_CURL=1 before executing the fetch. This provided me with some more information: 
 ```
 14:49:34.276162 http.c:774              == Info: schannel: disabled automatic use of client certificate
14:49:34.313837 http.c:774              == Info: schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
14:49:34.314072 http.c:774              == Info: Closing connection 0
```
 - The first line of this piece of output is interesting. The repositories causing problems require a p12 client certificate I have installed. 
 - I believe this might be caused by the upgrade to cURL v7.77.0. Looking in the cURL repository led me to this commit: 
 
```
commit 54e747501626b81149b1b44949119d365db82004
Author: Jay Satiro <raysatiro@yahoo.com>
Date:   Sat Feb 27 16:27:31 2021 -0500

    schannel: Disable auto credentials; add an option to enable it

    - Disable auto credentials by default. This is a breaking change
      for clients that are using it, wittingly or not.

    - New libcurl ssl option value CURLSSLOPT_AUTO_CLIENT_CERT tells libcurl
      to automatically locate and use a client certificate for
      authentication, when requested by the server.

    - New curl tool options --ssl-auto-client-cert and
      --proxy-ssl-auto-client-cert map to CURLSSLOPT_AUTO_CLIENT_CERT.

    This option is only supported for Schannel (the native Windows SSL
    library). Prior to this change Schannel would, with no notification to
    the client, attempt to locate a client certificate and send it to the
    server, when requested by the server. Since the server can request any
    certificate that supports client authentication in the OS certificate
    store it could be a privacy violation and unexpected.

    Fixes https://github.com/curl/curl/issues/2262
    Reported-by: Jeroen Ooms
    Assisted-by: Wes Hinsley
    Assisted-by: Rich FitzJohn

    Ref: https://curl.se/mail/lib-2021-02/0066.html
    Reported-by: Morten Minde Neergaard

    Closes https://github.com/curl/curl/pull/6673
 ```
 - The problem this leaves me with, is that I can't find a way to set this option in Git, so the old behaviour can be opted in to. I would expect a configuration value  (starting with "http.schannel"), but I cannot find one. I was actually very happy with the behaviour out of the box (where the certificate was automatically picked up from the Windows certificate store and sent to the server). 
 
 I hope this analysis helps to figure out a solution for anyone experiencing this problem.

### PR DESCRIPTION
**Pull request by pascalmuller**
This adds support for a new http.sslAutoClientCert config value.

In cURL 7.77 or later the schannel backend does not automatically send
client certificates from the Windows Certificate Store anymore.

This config value is only used if http.sslBackend is set to "schannel",
and can be used to opt in to the old behavior and force cURL to send
client certificates.

This fixes #3292

### CODE REVIEW

**Comment by pascalmuller** [comment]
I have some doubts, including: 

- Should this behavior be opt-in (as I have currently implemented it), or opt-out?
- I'm unsure about variable naming
- I'm unsure if the documentation I added is good enough to be understandable by anyone. 

I apologize if this PR is not up to the standards that are expected, but please be patient with me. This is my first attempt to contribute, so I might need help to get this Pull Request up to par and ready to merge. 

I really hope we can get the bug fixed soon.

File: http.c [hunk 1]
```diff
@@ -179,6 +179,8 @@ static int http_schannel_check_revoke_mode =
  */
 static int http_schannel_use_ssl_cainfo;
 
+static int http_schannel_auto_client_cert = 0;
```
Comment (dscho) [inline http.c:182]: `static` variables are implicitly initialized, therefore the ` = 0` is unneeded. Let's drop it.

Also, cURL's naming does not specify that this is specific to Secure Channel, so I would also drop the `schannel_` infix.

File: http.c [hunk 2]
```diff
@@ -920,13 +927,25 @@ static CURL *get_curl_handle(void)
...
 #endif
+		}
+
+		if (http_schannel_auto_client_cert) {
+#if LIBCURL_VERSION_NUM >= 0x074d00
+			ssl_options |= CURLSSLOPT_AUTO_CLIENT_CERT;
+#endif
+		}
+
+		if (ssl_options != 0) {
```
Comment (dscho) [inline http.c:946]: In Git's source code, we use the short form `if (ssl_options)`, and we frequently avoid the curly brackets around single statements (which I would find more readable in this instance).

**Comment by dscho** [comment]
Thank you so much for working on this. I always like it when users reporting an issue take the opportunity to become contributors and bring about the change they'd like to see. It makes maintaining a lot more fun that way.

Apart from the comments I added to the diff, could I ask for the following changes in the commit message?

1. we typically continue in lower-case after the "<area>:" part, and try to keep the oneline shorter; I would suggest using the oneline "http: optionally send SSL client certificate"
2. Could you write out the URL of the ticket in the "This fixes" line? I plan on shepherding this patch to the Git project, where the ticket number on its own would be misleading.
 
> I have some doubts, including:
> 
> * Should this behavior be opt-in (as I have currently implemented it), or opt-out?

Since cURL made it opt-in (for privacy reasons), I think you did the right thing.

> * I'm unsure about variable naming

As I said, I think we can drop the `schannel_` infix. Who knows whether cURL will use this flag for other TLS backends, too?

> * I'm unsure if the documentation I added is good enough to be understandable by anyone.

Personally, I find it very readable. Thank you!

> I apologize if this PR is not up to the standards that are expected, but please be patient with me. This is my first attempt to contribute, so I might need help to get this Pull Request up to par and ready to merge.

This PR is a really good start, and I believe that we'll need only one round of updates to get it in. You did pretty well, in particular as a first-time contributor!

**Comment by pascalmuller** [comment]
I made the requested changes. Thanks for your time and your suggestions so far; I appreciate it.

**Comment by dscho** [comment]
> 
> 
> I made the requested changes. Thanks for your time and your suggestions so far; I appreciate it.

I do not see the changes in https://github.com/git-for-windows/git/compare/3de1d46786a2326f65ab2e155c6e9762fac6a8e4..46c25af92ec6f9271691d5447c28d2d523358b81. Maybe you called `git commit --amend` without staging the changes first? Happens to me all the time...

**Comment by pascalmuller** [comment]
> > I made the requested changes. Thanks for your time and your suggestions so far; I appreciate it.
> 
> I do not see the changes in https://github.com/git-for-windows/git/compare/3de1d46786a2326f65ab2e155c6e9762fac6a8e4..46c25af92ec6f9271691d5447c28d2d523358b81. Maybe you called `git commit --amend` without staging the changes first? Happens to me all the time...

You're right. Stupid mistake on my part. Should be fixed now.

**Comment by dscho** [comment]
> You're right. Stupid mistake on my part. Should be fixed now.

Nah, it is a common mistake, no need to be hard on yourself. Thank you for taking care of it so swiftly!

**Review by dscho — APPROVED** [review]
Excellent! I'll wait for the CI to pass, and then merge. That should trigger [the "Git artifacts" Azure Pipeline](https://dev.azure.com/git-for-windows/git/_build?definitionId=34), and once that run finished, an Azure Release Pipeline will upload [the new snapshot](https://wingit.blob.core.windows.net/files/index.html)).

**Comment by dscho** [comment]
Thank you so much @pascalmuller!
