### PR TITLE
rebase-merges: improve --rebase-merges label generation

### LINKED ISSUE #2307: rebase with --rebase-merges fails to create refs with valid names
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

>git --version --build-options
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.1268]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing that I would believe would be of interest

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
>git rebase --rebase-merges origin/master
```
 - What did you expect to occur after running these commands?

A normal rebase procedure with or without merge conflicts

 - What actually happened instead?

I got the following output :
```
>git rebase --rebase-merges origin/master
error: refusing to update ref with bad name 'refs/rewritten/Merged-PR-183:-Handling-for-message'
hint: Could not execute the todo command
hint:
hint:     label Merged-PR-183:-Handling-for-message
hint:
hint: It has been rescheduled; To edit the command before continuing, please
hint: edit the todo list first:
hint:
hint:     git rebase --edit-todo
hint:     git rebase --continue
```
Which was resolved after manually replacing all refs with the colon (':') character with a valid character.  This led me to believe that the auto-generated labels led to invalid refnames, one would expect the auto-generated refs to be valid.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

### PR DESCRIPTION
**Pull request by ROGERSM94**
Resolves #2307 by replacing all non-alphanumeric ascii characters with '-' and appending an _ to prevent clashes with reserved windows filenames.

### CODE REVIEW

**Comment by PhilipOakley** [comment]
I believe the sign off should be the proper name you go by, rather than an abbreviation.

If changing the commit message, you should mention that the underlying issue is in the allowable characters on NTFS and FAT file systems as the label names effectively create refs on the file system. 
(i.e. tell about the underlying symptom, rather than the code change, which is obvious).

A simple force push of the updated PR branch is all that's needed to do an update.

Otherwise LGTM. At least it fixes the primary problem of colon characters in merge messages.

File: sequencer.c [hunk 1]
```diff
@@ -4635,9 +4635,13 @@ static int make_script_with_merges(struct pretty_print_context *pp,
 		else
 			strbuf_addbuf(&label, &oneline);
 
+		/* sanitize label */
 		for (p1 = label.buf; *p1; p1++)
 			if (isspace(*p1))
 				*(char *)p1 = '-';
+			/* check if non alphanumeric ascii character */
```
Comment (dscho) [inline sequencer.c]: I think we should also explain the `*p1 & 0x80` part, i.e. something like this instead:

```c
/*
 * Replace non-alphanumeric characters by dashes, as they might be illegal in
 * file names (and hence in ref names).
 *
 * Note that we retain non-ASCII UTF-8 characters (identified via the most
 * significant bit). They should be all acceptable in file names.
 */
```

Comment (ROGERSM94) [reply sequencer.c]: I added in that comment as you're probably right about that

**Comment by ROGERSM94** [comment]
Hope this update makes it look a bit better

File: sequencer.c (hunk 1 above)
Comment (dscho) [reply sequencer.c]: I think that "check if non alphanumeric ascii character" is a bit misleading: we want to retain _alpha-numeric ASCII* characters, but that comment tells me that we want to retain *non-*alpha-numeric ones.

File: sequencer.c [hunk 2]
```diff
@@ -4635,9 +4635,13 @@ static int make_script_with_merges(struct pretty_print_context *pp,
...
+			else if (!(*p1 & 0x80) && !isalnum(*p1))
+				*(char *)p1 = '-';
```
Comment (dscho) [inline sequencer.c]: As you pointed out in a follow-up PR comment, these two `if` conditions should be consolidated, as the conditional code is the _exact_ same in both cases: replace the current character by a dash.

File: sequencer.c (hunk 1 above)
Comment (dscho) [reply sequencer.c]: Actually, we want to retain non-ASCII UTF-8 characters, so what I said does not make too much sense. But that one-liner comment is still incomplete... I fixed it by using the verbose comment (after editing it slightly).
