### PR TITLE
rmdir: align behavior on Windows when called on symlinks

### LINKED ISSUE #2967: "git rebase" breaks symbolic link .git/logs when used together with repo-tool
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.631]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Google's repo-tool is used.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

  _NOTE1: I've created a test environment on my github to show this issue. It consists of a repository for manifest used by repo tool and a repository for pseudo source code_
  _NOTE2: repo-tool is needed to reproduce the issue but the issue itself is not with the repo-tool but with git for Windows, I think._

Run the following commands to see the issue:
```
repo init -u https://github.com/bossx91/test-repo-manifest -b main
repo sync
cd repo1
git checkout -t github/test
git rebase github/main
cd ..
repo sync
```
 - What did you expect to occur after running these commands?

I expected repo-tool sync succesfully.

 - What actually happened instead?

repo sync failed because **symlink in repo1/.git/logs has been broken after ```git rebase github/main``` has been run**.

 - How to see the issue more clearly?
 
 Run the commands above until this point (included): ```git checkout -t github/test```
 Now, ```cd``` into .git under repo1 folder.
 Run ```ls``` and see that "logs" is a symbolic link that points to the repo-tool's version of logs.
 Run ```git rebase github/main``` inside "repo1".
 Again ```cd``` into .git and see that "logs" is no longer a link but a folder (I suspect that this just copied the logs from where the link was potinng to before)

 - Additional information
 
This issue does not arise in Linux or WSL. In there, rebase command does not break the symbolic link, "logs"  but instead updates the real logs folder.

- What I've tried to solve this issue

```export MSYS=winsymlinks:nativestrict```
```git config --system core.symlinks true```
```git config --global core.symlinks true```
_Running Git for Windows as admin_

But none of the above have helped.
 
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/bossx91/test-repo-manifest - repository for manifest file for repo-tool
https://github.com/bossx91/test-repository1 - repository for pseudo source code

### PR DESCRIPTION
**Pull request by thombet**
Fixes #2967 

When performing a rebase, `rmdir()` is called on the folder `.git/logs`. On Linux `rmdir()` exits without deleting anything in case `.git/logs` is a symbolic link but the Windows equivalent (`_rmdir`) does not behave the same and removes the folder if it is symlink which generates issues especially when Repo is used.
This commit updates `mingw_rmdir()` so that its behavior is the same as Linux `rmdir()` in case of symbolic links.

Some remarks:
* I asked confirmation to Microsoft about the actual behavior of `_rmdir()` with symlinks but I didn't get an answer yet so my conclusions are only based on what I saw while debugging on Windows 10 with Git Bash.
* I created a "rebase" test case because this problem was found initially when performing "git rebase" but in the end the commit applies to `mingw_rmdir()` in general. Moreover I think it is in line with this part of the contribution guidelines: `The Git community prefers functional tests using the full git executable, so try to exercise your new code using git commands before creating a test helper.` But if you think a test case dedicated to `mingw_rmdir()` should be created, please let me know.
* Kudos to @rimrul for helping me choose the correct value for `errno` :)

### CODE REVIEW

File: compat/mingw.c [hunk 1]
```diff
@@ -560,6 +560,20 @@ int mingw_rmdir(const char *pathname)
...
+		 * (in the context of Repo for instance). So before calling _wrmdir()
+		 * we first check if the path is a symbolic link. If it is, we exit
+		 * and return the same error as Linux rmdir() in this case (ENOTDIR).
+		 */
+		struct stat sb;
+		if (!mingw_lstat(pathname, &sb) && S_ISLNK(sb.st_mode)) {
+			errno = ENOTDIR;
+			break;
+		}
+
```
Comment (dscho) [inline compat/mingw.c:576]: Could you move this to before the loop? The loop retries to delete a directory in case it is still in use, and it does not really make sense to ask over and over again whether it is a symbolic link or not.

Also, regarding the commit message:

> issues especially when Repo is used.

The `repo` tool is not shipped with Git for Windows, and is actually not all that known outside of a small circle of Git users. It would make sense to elaborate a bit on what it is, and link to its homepage (if it has one).

Speaking of the commit message, I would love to see a paragraph added that talks about [`RemoveDirectoryW()`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-removedirectoryw) having the same problem as `_wrmdir()`, and it is even documented:

> RemoveDirectory removes a directory junction, even if the contents of the target are not empty; the function removes directory junctions regardless of the state of the target object. For more information on junctions, see [Hard Links and Junctions](https://docs.microsoft.com/en-us/windows/desktop/FileIO/hard-links-and-junctions).

Well, _technically_ it does not talk about reparse points in general but only specifically about junctions. But the point is that we cannot expect that function to treat reparse points in the way we want, in general, and therefore we must take manual precautions (and there is no `RemoveDirectoryExW()` that would hypothetically let the caller specify whether it is okay to delete reparse points).

Since that documentation also talks about hard links, I briefly investigated whether `_wrmdir()` could potentially remove hardlinks by mistake. But hardlinks can only link to files, not directories, and `_wrmdir()` correctly errors out upon trying to remove hardlinks.

File: t/t3438-rebase-git-logs-symlink.sh [hunk 2]
```diff
@@ -0,0 +1,46 @@
+#!/bin/sh
+
+test_description='git rebase when .git/logs is a symlink
+
+This test runs a "git rebase" in a repository where .git/logs
+is a symlink and checks that the symlink is not removed.
+If the system does not support symlinks, the whole test will
+be skipped. On Windows, the symlinks may be enabled by granting
+the "Create Symbolic Links" user right and settting the environment
```
Comment (dscho) [inline t/t3438-rebase-git-logs-symlink.sh:9]: s/settting/setting/

File: t/t3438-rebase-git-logs-symlink.sh [hunk 3]
```diff
@@ -0,0 +1,46 @@
+#!/bin/sh
+
+test_description='git rebase when .git/logs is a symlink
```
Comment (dscho) [inline t/t3438-rebase-git-logs-symlink.sh:3]: This is an awfully specific test in a sprawling test suite. Could we make this a bit more generic, or even better: could we put this into an existing `t34*` test script?

File: t/t3438-rebase-git-logs-symlink.sh [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+# Create a rebase situation with 2 commits on a branch and another commit which
+# diverges from them. The 2 commits are created on a branch called
+# "rebase-reference" so that the rebase command that will be used later does
+# not depend on the name of the default branch (master, main, etc.).
+test_expect_success 'Create commits to prepare rebase' '
+    git switch --create rebase-reference &&
+    git commit --allow-empty -m "Initial commit" &&
+    git commit --allow-empty -m "Second commit" &&
+    git switch --create branch-to-rebase HEAD~1 &&
+    git commit --allow-empty -m "Dummy commit to rebase"
```
Comment (dscho) [inline t/t3438-rebase-git-logs-symlink.sh:29]: That's a lot of commands to essentially set up the stage for a simple rebase. How about this instead?

```sh
test_commit initial &&
test_commit second
```

The test case can then consist of the command `git rebase -f HEAD^` followed by a test that verifies that `.git/logs` is still a symbolic link.

File: t/t3438-rebase-git-logs-symlink.sh [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+'
+
+test_expect_success 'Turn .git/logs into a symlink' '
+    mv .git/logs actual_logs &&
+    ln -s ../actual_logs .git/logs
```
Comment (dscho) [inline t/t3438-rebase-git-logs-symlink.sh:34]: As you pointed out in the comment above, `ln -s` won't work by default in an MSYS setup. However, that is exactly what all of the CI/PR builds run.

As a consequence, I fear that this test script will only ever run on Linux/macOS/FreeBSD, where we _know_ that things work.

A better idea might be to add a new test case to an existing `t34*` script, guarded by the `MINGW` prereq, that first verifies that it _can_ create a symbolic link, and that does not use `ln -s` for it, but `mklink /s` to do so, and if  it cannot create the symlink, simply renames the `logs` directory back, otherwise runs through the simple `rebase` and verifies that the symbolic link still exists.

**Comment by thombet** [comment]
Thank you for the review and the very interesting suggestions @dscho !
I will take them into account and publish an update.

What is the policy in this repository for updates of PR which are not independent commits? Should I amend and force push my update? Or should I push another commit and you or I will squash them before merging the PR?

**Comment by dscho** [comment]
Please amend and force-push. The cleaner the commit history, the easier it will be for me to upstream those changes.

File: compat/mingw.c (hunk 1 above)
Comment (thombet) [reply compat/mingw.c:576]: I moved the code and I updated the commit message based on your recommendations.
Please let me know if it is what you had in mind.

File: t/t3438-rebase-git-logs-symlink.sh (hunk 3 above)
Comment (thombet) [reply t/t3438-rebase-git-logs-symlink.sh]: I only read `t/README` and I didn't read the "Add regressions tests" wiki page so I missed the information that it was better to add a test case in an existing test, sorry for this.
I created a test case in `t3400-rebase.sh` instead.

File: t/t3438-rebase-git-logs-symlink.sh (hunk 4 above)
Comment (thombet) [reply t/t3438-rebase-git-logs-symlink.sh]: `git rebase -f HEAD^` is much better, thanks for the suggestion :)

File: t/t3438-rebase-git-logs-symlink.sh (hunk 5 above)
Comment (thombet) [reply t/t3438-rebase-git-logs-symlink.sh]: I decided to create the `SYMLINKS_WINDOWS` prerequisite based on the `SYMLINKS` prerequisite which uses `mklink` instead of `ln` in case it is useful to someone else in the future.

File: compat/mingw.c (hunk 1 above)
Comment (dscho) [reply compat/mingw.c:576]: I like the new commit message!

File: t/t3400-rebase.sh [hunk 6]
```diff
@@ -406,4 +406,18 @@ test_expect_success 'refuse to switch to branch checked out elsewhere' '
...
+test_expect_success MINGW,SYMLINKS_WINDOWS 'rebase when .git/logs is a symlink' '
+	git checkout main &&
+	mv .git/logs actual_logs &&
+	cmd //c "mklink /D .git\logs ..\actual_logs" &&
+	git rebase -f HEAD^ &&
+	test -L .git/logs &&
+	rm .git/logs &&
+	mv actual_logs .git/logs
+'
+# Note: `test -L` will fail if ".git/logs" is not a symlink OR if ".git/logs"
```
Comment (dscho) [inline t/t3400-rebase.sh:418]: IMHO we do not need this code comment (it would be the first such code comment in t3400, I believe).

**Review by dscho — APPROVED** [review]
Apart from the code comment in t3400, I think this is ready to go!

File: t/t3400-rebase.sh (hunk 6 above)
Comment (thombet) [reply t/t3400-rebase.sh]: I think comments are most of the time useful but you're the boss here so I removed them 😉

**Comment by thombet** [comment]
Comments removed, commit amended, branch rebased and PR updated.
Thanks for your guidance 👍

**Review by dscho — APPROVED** [review]
Very nice!

**Comment by thombet** [comment]
@dscho some tests failed in the CI: is it expected or should I analyze the failure?

**Comment by rimrul** [comment]
The failing test is `t5702.57` on macOS (gcc only). I don't really see how the changes in this PR could have caused that.

**Comment by dscho** [comment]
> 
> 
> The failing test is `t5702.57` on macOS (gcc only). I don't really see how the changes in this PR could have caused that.

It looks like a segmentation fault of one sort or other. It is admittedly not yet easy enough to get to the full log of the actual failure. You have to expand the "ci/print-test-failures.sh" task's log and then search for "not ok". Here it is: https://github.com/git-for-windows/git/runs/3191969335#step:5:20818

> ```
> ++ echo 'test_must_fail: died by signal 13: git -c protocol.version=2 -c transfer.fsckobjects=1 -c fetch.uriprotocols=http,https clone http://127.0.0.1:5702/smart/http_parent http_child'
> test_must_fail: died by signal 13: git -c protocol.version=2 -c transfer.fsckobjects=1 -c fetch.uriprotocols=http,https clone http://127.0.0.1:5702/smart/http_parent http_child
> ++ return 1
> error: last command exited with $?=1
> not ok 57 - packfile-uri with transfer.fsckobjects fails on bad object
> ```

I _think_ I saw this before, but if that is the case then it is a pretty rare flake. I just re-ran the build.

**Comment by dscho** [comment]
> I just re-ran the build.

... and it figured out that there was a successful build already with the same tree, so it skipped it with success: https://github.com/git-for-windows/git/runs/3199628097

Which means that indeed, this is a flake, and definitely not the fault of this PR. @thombet thank you for being so diligent and to offer to investigate further!

**Comment by thombet** [comment]
> @thombet thank you for being so diligent and to offer to investigate further!

You're welcome, I don't want to be the one who breaks Git 😅
